# Config format schema number
format_version: 1
clip:
  path: "/root/data/jcenaa/dataset_av/clip/fcn_cityscapes_256x512_20201226.pt"

###################
## Model options
model_params:
  model_architecture: "arch_cmd_fusion"

  input_dims: 4
  spatial_shape:
    - 1000
    - 1000
    - 60
  scale_list:
    - 2
    - 4
    - 8
    - 16

  hiden_size: 128
  num_classes: 20
  backbone_2d: resnet101
  pretrained2d: False

###################
## Dataset options
dataset_params:
  training_size: 23203
  dataset_type: "point_image_dataset_semkitti"
  pc_dataset_type: "SemanticKITTI_polarmix_1"
  collate_type: "collate_fn_default"
  ignore_label: 0
  label_mapping: "./config/label_mapping/semantic-kitti-all.yaml"

  # 2D augmentation
  eval_ood: False
  bottom_crop:
    - 1200
    - 360
  color_jitter:
    - 0.4
    - 0.4
    - 0.4
  flip2d: 0.5
  image_normalizer:
    - [0.485, 0.456, 0.406]
    - [0.229, 0.224, 0.225]
  max_volume_space:
    - 50
    - 50
    - 2
  min_volume_space:
    - -50
    - -50
    - -4
  seg_labelweights:
    - 0
    - 55437630
    - 320797
    - 541736
    - 2578735
    - 3274484
    - 552662
    - 184064
    - 78858
    - 240942562
    - 17294618
    - 170599734
    - 6369672
    - 230413074
    - 101130274
    - 476491114
    - 9833174
    - 129609852
    - 4506626
    - 1168181

  train_data_loader:
    data_path: "/root/data/jcenaa/dataset_av/semantickitti/dataset/sequences/"
    batch_size: 4
    shuffle: True
    num_workers: 8
    rotate_aug: True
    flip_aug: True
    scale_aug: True
    transform_aug: True
    dropout_aug: True

  val_data_loader:
    data_path: "/root/data/jcenaa/dataset_av/semantickitti/dataset/sequences/"
    shuffle: False
    num_workers: 8

    # normal test
    batch_size: 1
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False


###################
## Train params
train_params:
  max_num_epochs: 128
  learning_rate: 0.01
  optimizer: SGD  # [SGD, Adam]
  lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-4
  finetune: True
  lambda_seg2d: 4
  lambda_xm: 0.05
